# Generated by Django 4.2 on 2023-05-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_daily_error_event_note_delete_profil_daily_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='bed_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event'),
        ),
    ]
