# Generated by Django 4.2 on 2023-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_daily_bed_time_alter_daily_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='bed_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='event',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='pray',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
